version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "16"

    volumes:
      - ..:/workspace:cached
    command: sleep infinity

